version: '3.8'
services:
  st_api_nlp:
    container_name: st_api_nlp
    build: ./nlp_api/
    ports:
      - "3002:8000"
    volumes:
      - ./nlp_api/src:/app/src
    networks:
      - my_network
  st_api_backend:
    container_name: st_api_backend
    build: ./backend/
    ports:
        - '3000:3000'
    volumes:
        - ./backend/src:/app/src
    depends_on:
        - st_mysql
    networks:
      - my_network
  st_mysql:
    container_name: st_mysql
        - mysql

  st_api_transcription: 
    build: ./transcription_api/
    ports:
        - '3008:3008'
    volumes:
        - ./transcription_api/src:/app/src
    depends_on:
        - mysql
        - rabbitmq
  mysql:
    image: mysql:8
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: dash
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
        - '3306:3306'
    volumes:
        - mysql_data:/var/lib/mysql
        - ./backend/scripts:/docker-entrypoint-initdb.d
    networks:
      - my_network
  st_rabbitmq:
    container_name: st_rabbitmq
    image: 'rabbitmq:3-management'
    ports:
        - '5672:5672'
        - '15672:15672'
    environment:
        RABBITMQ_DEFAULT_USER: 'guest'
        RABBITMQ_DEFAULT_PASS: 'guest'
    networks:
      - my_network
volumes:
    mysql_data:  
networks:
    my_network:
